### ISSUE TITLE
R键bug

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorldExp#13]
造一堵很高的墙，站在墙角，视线对着墙顶部，按R键（未开飞行、穿墙），然后一直飞到墙的顶部，就会发现掉不下来。

**Comment by ascchrvalstr** [comment]
![bug](https://cloud.githubusercontent.com/assets/12978630/12070340/0b3104ec-b0a9-11e5-914b-bfd24da07786.png)

**Comment by harrynull** [comment]
这是特性，R键有飞行功能。顶部掉不下来请确定使用的是0.4.10及以上的正式版

**Comment by harrynull** [comment]
经测试，0.4.10正式版没有出现掉不下来的问题
