### ISSUE TITLE
穿墙问题

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorldExp#15]
按F1，升到比较高的位置，然后再按F1，在掉落过程中开启穿墙，会出现画面振动的问题。

**Comment by HydroH** [comment]
只要在速度较高时开启穿墙就会发生，例如同时按下R+F4时（前方无阻挡）

**Comment by harrynull** [comment]
@qiaozhanrong 你的锅……（吧）

**Comment by bridgekat** [comment]
修复完毕 604394e00287f39b21382ea35bf867695a4551e0
