### ISSUE TITLE
破坏方块时物品栏里的每一行都会多出一个方块

### ISSUE THREAD

**Issue by HydroH** [Infinideastudio/NEWorldExp#20]
![01](https://cloud.githubusercontent.com/assets/14823453/12220135/90377cb6-b79d-11e5-9c1a-32629c83e922.png)
破坏一个方块之前

![02](https://cloud.githubusercontent.com/assets/14823453/12220136/903a810e-b79d-11e5-8f30-fe5fa805d37e.png)
破坏一个方块之后

**Comment by HydroH** [comment]
另外打开物品栏时不能截图

**Comment by ascchrvalstr** [comment]
@abc612008 你的锅（吧

**Comment by harrynull** [comment]
感谢反馈，已修复 7416048c8719e3de68eedaa79dcf75946c90747b
