### ISSUE TITLE
在非飞行模式下按R/F 画面会抖动一下

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorldExp#22]

**Comment by HydroH** [comment]
非飞行模式下按住R/F会导致垂直速度不变（如下落时按下R会匀速下落，跳起时按下R会匀速上升，按住R走下边缘可以悬浮等等）

**Comment by bridgekat** [comment]
这个问题我们正在解决

**Comment by harrynull** [comment]
已修复 见 fdc96ee5debf66f7d858aa758e6d4896a7126c4f
