### ISSUE TITLE
[0.5.0 v38]選擇世界界面無論任何情況也不能被翻譯

### ISSUE THREAD

**Issue by jacky8399** [Infinideastudio/NEWorldExp#24]
不要跟我說Work As Intended = =
![image](https://cloud.githubusercontent.com/assets/7542810/12384597/c7ecd85c-bdee-11e5-89c0-f96c4bb51e90.png)
(｡･ω･｡)如圖這是英文版的NEWorld
![image](https://cloud.githubusercontent.com/assets/7542810/12384607/dcd7b520-bdee-11e5-887d-f53558f85c26.png)
!!!∑(ﾟДﾟノ)ノ然而進入到世界選擇菜單 卻出現了一堆野生的亂碼

**Comment by MichaelRix** [comment]
因爲他們根本沒有翻譯。非常抱歉。

**Comment by bridgekat** [comment]
有几个菜单没设置翻译。。。

**Comment by bridgekat** [comment]
现在已经解决
