### ISSUE TITLE
[0.5.0 v38]繁體中文翻譯仍需經過Unicode本地化

### ISSUE THREAD

**Issue by jacky8399** [Infinideastudio/NEWorldExp#25]
如題
繁體中文翻譯文件仍然需要經過Unicode本地化為簡體中文，才能正常顯示
![image](https://cloud.githubusercontent.com/assets/7542810/12384855/696bd06e-bdf1-11e5-9759-2a3beae2363f.png)
未簡體中文本地化
![image](https://cloud.githubusercontent.com/assets/7542810/12384867/894ab422-bdf1-11e5-9002-a7f9c1fc1193.png)
 簡體中文本地化

**Comment by bridgekat** [comment]
？

**Comment by bridgekat** [comment]
貌似把语言文件保存成ANSI编码格式就好了。。。
