### ISSUE TITLE
[v5.0] 自C++版本以來存檔BUG

### ISSUE THREAD

**Issue by MichaelRix** [Infinideastudio/NEWorldExp#27]
你們可以在世界菜單輕鬆創建一個包含"&"或者"&&"的世界。
然而刪除不了：

> 系統找不到指定的文件。

叫你們偷懶，快去把`system()`都換掉！

**Comment by ascchrvalstr** [comment]
【其实https://github.com/ascchrvalstr/wxNEWorld 里面已经没有这个bug了

**Comment by bridgekat** [comment]
已经修复

**Comment by bridgekat** [comment]
3bb378515ef85ccc573735e3709a0dc5ea438a56

**Comment by bridgekat** [comment]
我去为啥没用
ad9b2c51563a33f3f790ae462f80497f29a9f920

**Comment by bridgekat** [comment]
ok

**Comment by harrynull** [comment]
结果还是用的system吗……@qiaozhanrong

**Comment by bridgekat** [comment]
@abc612008 是啊。。。只不过加上了双引号
