### ISSUE TITLE
另一个

### ISSUE THREAD

**Issue by ciwomuli** [Infinideastudio/NEWorldExp#30]
可以吧opengl换成3.3+

**Comment by ascchrvalstr** [comment]
兼容性会大幅度降低以及如果换的话貌似要改几千行代码

**Comment by ciwomuli** [comment]
现在用2.0的机器不多了，而且改代码不是你们最高兴吗

**Comment by bridgekat** [comment]
最重要的问题是兼容性会大幅度降低
谁说2.0不多了，我有台电脑就是2.0的
NEWorld FirstMod的作者还在用GL1.5的显卡
就连NW开发者之一SSS的GL版本也才3.1
