### ISSUE TITLE
建议把NEWorld logo矢量化

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorldExp#38]
高分屏下分辨率不足，建议加强

**Comment by HydroH** [comment]
PDF与SVG矢量文件已完成
[NEWorld.pdf](https://github.com/Infinideastudio/NEWorld/files/120141/NEWorld.pdf)

**Comment by DWVoid** [comment]
需要pdf读写代码 @HydroH

**Comment by HydroH** [comment]
@DREAMWORLDVOID PDF可以轻易转换为SVG等矢量格式 或者直接向我要SVG的也行 GitHub没法上传SVG

**Comment by SuperSodaSea** [comment]
其实目前可以简单点做，可以做一张大图，或者用几张小图拼起来

**Comment by DWVoid** [comment]
@HydroH 直接发在项目里面的Texture文件夹下，0.5.0分支，发SVG格式

**Comment by bridgekat** [comment]
矢量化的话就相当于用OpenGL的图元画Logo了。。。不过我建议把Filter调成GL_LINEAR，或者限制PPI缩放使其只能放大2的整数次方倍以改进效果
