### ISSUE TITLE
需要更新zh_TW翻译

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorldExp#39]

**Comment by jacky8399** [comment]
![2 ygfhgm72to vi8 5](https://cloud.githubusercontent.com/assets/7542810/12887570/2927d0e6-ceb0-11e5-8dac-d71eba9504ab.jpg)
我(好像)是負責人來打我啊 @DREAMWORLDVOID  QAQ

**Comment by jacky8399** [comment]
可以close了吧

**Comment by bridgekat** [comment]
你让jacky去弄吧233

**Comment by jacky8399** [comment]
![4lqrqo vi6 3j8 5 1 xs2](https://cloud.githubusercontent.com/assets/7542810/13050956/91cc7170-d431-11e5-9c31-db9cca5d5068.jpg)
這怪異的叫法
