### ISSUE TITLE
亂碼問題

### ISSUE THREAD

**Issue by jacky8399** [Infinideastudio/NEWorldExp#4]
當在非中文(簡體)環境中運行NEWorld時，將會出現亂碼
~~就跟某Planeworld一樣~~

**Comment by harrynull** [comment]
请提供截图

**Comment by jacky8399** [comment]
有多難等我一下

**Comment by jacky8399** [comment]
![j5 bkrqh3 l tipbmo4eyp0](https://cloud.githubusercontent.com/assets/7542810/12008825/67ba030e-ac93-11e5-919d-327ef1894c48.png)

**Comment by ascchrvalstr** [comment]
一看就是不支持GB2312

**Comment by jacky8399** [comment]
JB2321...QAQ怪我咯 我是用戶

**Comment by harrynull** [comment]
暂时没有环境重现问题

**Comment by harrynull** [comment]
已确认已于0.4.10版本修复该BUG，请下载最新版本

**Comment by bridgekat** [comment]
部分菜单的乱码已经修复。。。
剩下未修复的菜单将以你的另一个issue为参考。。。
