### ISSUE TITLE
[诺亚圆舟]loadMods()完全没个卵用

### ISSUE THREAD

**Issue by jacky8399** [Infinideastudio/NEWorldExp#42]
![4mg srpi s5 vpksptk3 2y](https://cloud.githubusercontent.com/assets/7542810/12909576/577204e8-cf3d-11e5-8a05-4dcf3923ed6b.png)

**Comment by taxerap** [comment]
= =

**Comment by harrynull** [comment]
何以见得？

**Comment by bridgekat** [comment]
何以见得？

**Comment by bridgekat** [comment]
Mods文件夹里没有Mod当然没卵用了，不算bug
