### ISSUE TITLE
是时候加入硬度了

### ISSUE THREAD

**Issue by idkidknow** [Infinideastudio/NEWorldExp#44]
所有方块挖起来都一样快，不违和么……
设定好手挖方块的速度，硬度直接速度*时间就好了

**Comment by DWVoid** [comment]
好像已经有这个特性了

**Comment by DWVoid** [comment]
在A050已经加入，请耐心等待发布
const SingleBlock blockData[BLOCK_DEF_END + 1] = {
        //          方块名称          固体     不透明    半透明  可以爆炸  硬度
        SingleBlock("NEWorld.Blocks.Air"        , false , false , false , false,    0),
