### ISSUE TITLE
增加x64编译的lib（添加freetype和glfw的lib64）

### ISSUE THREAD

**Issue by dtcxzyw** [Infinideastudio/NEWorldExp#48]
即将上光线追踪

**Comment by dtcxzyw** [comment]
算了我自己找

**Comment by ghost** [comment]
个人一点微小的观点：Git只放源代码，库文件自己配置，因为有不同平台的开发者。这样是最好的。我连接GitHub的速度只有几KB/s，然后还经常克隆到一半突然连接被切断，看到你们往Git里面放库文件，我的内心是崩溃的啊啊啊啊啊！

**Comment by dtcxzyw** [comment]
然而我们现在的重心在windows版本上，以后会改

**Comment by dtcxzyw** [comment]
已完成
