### ISSUE TITLE
[Feature Request]我要多語言！QAQ

### ISSUE THREAD

**Issue by jacky8399** [Infinideastudio/NEWorldExp#7]
我要多語言啊喂
Null(853187773) 12:11:39
欢迎大家去发Issues
Null(853187773) 12:11:43
我都会认真解决的OAO
qiaozhanrong 2015/12/27 12:25:53
做多语言的时候
qiaozhanrong
文本从文件读取
qiaozhanrong
可以防止乱码
qiaozhanrong 2015/12/27 12:27:04
然而现在我们都懒的做多语言
(╯°Д°）╯︵ /(.□ . ) /(.□ . ) /(.□ . )不要那麼懶好嗎
(╯°□°）╯︵ ┻━┻這可是可以修復另外一個issue啊

**Comment by HydroH** [comment]
噫我有兴趣进行翻译工作

**Comment by harrynull** [comment]
@HydroH 也没几个词吧。。。233

**Comment by DWVoid** [comment]
我可以写代码，不过要下周才能完成，这周太忙

**Comment by DWVoid** [comment]
已经开做了

**Comment by bridgekat** [comment]
基本完成，然而繁体中文的语言文件准备让你来翻译23333
