### ISSUE TITLE
新特性建议

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorldExp#9]
插件系统；多语言支持；跨平台支持

**Comment by bridgekat** [comment]
只剩插件系统了
虽然跨平台不是很完美

**Comment by ascchrvalstr** [comment]
其实是根本不跨平台
会失去一大堆特性

**Comment by DWVoid** [comment]
跨平台其实不是太困难。刚刚看了微软的ref，其实用vs的vcpp就可以搞定所有的平台，就是移动平台部分的键盘和鼠标要变成触控，OpenGL要改成OpenGLES，其他部分基本都不用重写（而且，说真的，如果这次能成功的话NEWorld就能直接上AppStore了）
